# This is a basic workflow to help you get started with Actions

name: Covid daily scrapper

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '25 19 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
        pip install pytz
        pip install scipy
        pip install numpy
        pip install matplotlib
        python pakistan_data/scrap_data_to_csv.py
        cd pakistan_data/
        python csv_to_txt.py
        python analysis.py

    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Add updated csv file

        branch: ${{ github.head_ref }}
        file_pattern: pakistan_data/*.csv pakistan_data/*.png pakistan_data/*.txt
        commit_user_name: GitHub Actions Bot

    - name: install scipy, numpy, matlotlib
      run: |
