# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    # Runs a single command using the runners shell
    - name: upgrade pip
      run: python -m pip install --upgrade pip

    - name: install bs4
      run: pip install bs4

    - name: install requests
      run: pip install requests

    - name: install pytz
      run: pip install pytz

    # Scrap data to csv
    - name: run script
      run: python pakistan_data/scrap_data_to_csv.py

    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Add updated csv file

        branch: ${{ github.head_ref }}
        file_pattern: pakistan_data/pakistan_data.csv
        commit_user_name: GitHub Actions Bot